<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ConsultarDatosUsuarioService" targetNamespace="http://delegate.hb.link.fu.bna.com.ar/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://delegate.hb.link.fu.bna.com.ar/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://delegate.hb.link.fu.bna.com.ar/" schemaLocation="ConsultarDatosUsuarioService_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="version">
    <part name="parameters" element="tns:version">
    </part>

  </message>
  <message name="versionResponse">
    <part name="parameters" element="tns:versionResponse">
    </part>
  </message>
  <message name="esCliente">
    <part name="parameters" element="tns:esCliente">
    </part>
  </message>

  <message name="esClienteResponse">
    <part name="parameters" element="tns:esClienteResponse">
    </part>
  </message>
  <portType name="ConsultarDatosUsuarioDelegate">
    <operation name="esCliente">
      <input message="tns:esCliente" wsam:Action="http://delegate.hb.link.fu.bna.com.ar/ConsultarDatosUsuarioDelegate/esClienteRequest">
    </input>
      <output message="tns:esClienteResponse" wsam:Action="http://delegate.hb.link.fu.bna.com.ar/ConsultarDatosUsuarioDelegate/esClienteResponse">

    </output>
    </operation>
    <operation name="version">
      <input message="tns:version" wsam:Action="http://delegate.hb.link.fu.bna.com.ar/ConsultarDatosUsuarioDelegate/versionRequest">
    </input>
      <output message="tns:versionResponse" wsam:Action="http://delegate.hb.link.fu.bna.com.ar/ConsultarDatosUsuarioDelegate/versionResponse">
    </output>
    </operation>
  </portType>

  <binding name="ConsultarDatosUsuarioPortBinding" type="tns:ConsultarDatosUsuarioDelegate">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="esCliente">
      <soap12:operation soapAction=""/>
      <input>
        <soap12:body use="literal"/>
      </input>
      <output>
        <soap12:body use="literal"/>

      </output>
    </operation>
    <operation name="version">
      <soap12:operation soapAction=""/>
      <input>
        <soap12:body use="literal"/>
      </input>
      <output>
        <soap12:body use="literal"/>

      </output>
    </operation>
  </binding>
  <service name="ConsultarDatosUsuarioService">
    <port name="ConsultarDatosUsuarioPort" binding="tns:ConsultarDatosUsuarioPortBinding">
      <soap12:address location="http://10.7.232.26:80/ws_login_1_1/ConsultarDatosUsuarioService"/>
    </port>
  </service>
</definitions>

